# .github/workflows/ci.yml
name: CI Pipeline   

on:
  push:            
    branches:
      - main       
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies with npm ci (legacy peer deps for React 19 RC)"
          npm ci --legacy-peer-deps

      - name: Run Linter
        run: |
          echo "Running ESLint to check code quality"
          npm run lint

      - name: Run Tests
        run: |
          echo "Running Jest tests in CI mode"
          npm run test:ci

      - name: Build Application
        run: |
          echo "Building the application"
          npm run build
