# .github/workflows/ci.yml
name: CI Pipeline   

on:
  push:            
    branches:
      - main       
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.10'
          cache: 'npm'
      - name: Install dependencies
        run: |
          echo "Installing dependencies with npm ci (legacy peer deps)"
          npm ci --legacy-peer-deps
      - name: Run Linter
        run: |
          echo "Running ESLint to check code quality"
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.10'
          cache: 'npm'
      - name: Install dependencies
        run: |
          echo "Installing dependencies with npm ci (legacy peer deps)"
          npm ci --legacy-peer-deps
      - name: Run Tests
        run: |
          echo "Running Jest tests in CI mode"
          npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Simulate Deployment
        run: |
          echo "Deployment successful"
